version: "1.0"

# Constraints file to enforce architecture rules
constraints_file: CONSTRAINTS.md


services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dam
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5


tests:

  #
  # HEALTH TEST
  #
  - name: Health endpoint must respond
    request:
      method: GET
      url: http://localhost:8000/health
    expect:
      status: 200


  #
  # ASSET CREATION TEST
  #
  - name: Create asset
    request:
      method: POST
      url: http://localhost:8000/assets
    save:
      json:
        asset_id: asset_id
    expect:
      status: 200
      json:
        asset_id: "*"


  #
  # VERIFY INITIAL STATE
  #
  - name: Verify asset initial state is CREATED
    request:
      method: GET
      url: http://localhost:8000/assets/{{asset_id}}
    expect:
      status: 200
      json:
        asset_id: "{{asset_id}}"
        status: CREATED


  #
  # FILE UPLOAD TEST
  #
  - name: Upload asset file
    request:
      method: POST
      url: http://localhost:8000/assets/{{asset_id}}/upload
      files:
        file: harness_test_file.txt
    expect:
      status: 200


  #
  # VERIFY UPLOADED STATE
  #
  - name: Verify state becomes UPLOADED after upload
    request:
      method: GET
      url: http://localhost:8000/assets/{{asset_id}}
    expect:
      status: 200
      json:
        asset_id: "{{asset_id}}"
        status: UPLOADED


  #
  # WAIT FOR WORKER TO PROCESS
  #
  - name: Wait for worker processing
    wait: 6


  #
  # VERIFY FINAL READY STATE
  #
  - name: Verify asset reaches READY state
    request:
      method: GET
      url: http://localhost:8000/assets/{{asset_id}}
    expect:
      status: 200
      json:
        asset_id: "{{asset_id}}"
        status: READY


  #
  # VERIFY ASSET RETRIEVAL CONSISTENCY
  #
  - name: Verify asset retrieval remains consistent
    request:
      method: GET
      url: http://localhost:8000/assets/{{asset_id}}
    expect:
      status: 200
      json:
        asset_id: "{{asset_id}}"
        status: READY
